### ISSUE TITLE
Hygrotempo Decoder in Codec API

### ISSUE THREAD

**Issue by jvelasquezm1** [Watteco/Codec-API-LoRaWAN#5]
Hello,

I am currently using your Codec API for LoRaWAN and noticed that the `Hygrotemp'o` decoder is missing in the API, even though it is available through your online [tool](https://lora.watteco.fr/Lora/).

Are there any plans to include this decoder in an upcoming release?

Thanks in advance.

**Comment by 0Davgi0** [comment]
Hi,
For the `Hygrotemp'O`, you would need to used the `th` decoder.
Some of our sensors share the same codecs, a table explaining this should be available soon.

Best regards,
David

**Comment by ianchanning** [comment]
Great thanks!
